# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-03 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180408_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='docs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='exams',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='lessons',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='users',
            field=models.BooleanField(default=False),
        ),
    ]
