# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-09 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180504_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
