# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-13 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_role_exams_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='statement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Statement'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='theme',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
