# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-15 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180513_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Lesson'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statement',
            name='discipline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Discipline'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statement',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Group'),
            preserve_default=False,
        ),
    ]
