# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-16 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180515_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='discipline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Discipline'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Group'),
            preserve_default=False,
        ),
    ]
