# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-16 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180516_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examlist',
            name='exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Exam'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examlist',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Student'),
            preserve_default=False,
        ),
    ]
