# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-16 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20180516_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='homework',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
