# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-26 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20180517_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='disciplines',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='groups',
            field=models.BooleanField(default=False),
        ),
    ]
